return {
	-- "yetone/avante.nvim",
	-- -- keys = { "<leader>aa", "<leader>ae" },
	-- event = "VeryLazy",
	-- version = false, -- Never set this value to "*"! Never!
	-- ---@module 'avante'
	-- ---@type avante.Config
	-- opts = {
	-- 	instructions_file = "avante.md",
	-- 	---@alias Provider "claude" | "openai" | "azure" | "gemini" | "cohere" | "copilot" | string
	-- 	---@type Provider
	-- 	provider = "copilot",
	-- 	auto_suggestions_provider = "copilot",
	-- 	---@alias Mode "agentic" | "legacy"
	-- 	---@type Mode
	-- 	mode = "agentic",
	-- 	providers = {
	-- 		claude = {
	-- 			endpoint = "https://api.anthropic.com",
	-- 			auth_type = "api",
	-- 			model = "claude-3-5-sonnet-20241022",
	-- 			timeout = 30000, -- Timeout in milliseconds
	-- 			extra_request_body = {
	-- 				temperature = 0.75,
	-- 				max_tokens = 4096,
	-- 			},
	-- 		},
	-- 	},
	-- 	dual_boost = {
	-- 		enabled = false,
	-- 		first_provider = "copilot",
	-- 		second_provider = "claude",
	-- 		prompt = "Based on the two reference outputs below, generate a response that incorporates elements from both but reflects your own judgment and unique perspective. Do not provide any explanation, just give the response directly. Reference Output 1: [{{provider1_output}}], Reference Output 2: [{{provider2_output}}]",
	-- 		timeout = 60000, -- Timeout in milliseconds
	-- 	},
	-- 	behaviour = {
	-- 		auto_suggestions = false, -- Experimental stage
	-- 		auto_set_highlight_group = true,
	-- 		-- auto_set_keymaps = true,
	-- 		auto_apply_diff_after_generation = false,
	-- 		support_paste_from_clipboard = false,
	-- 		minimize_diff = true, -- Whether to remove unchanged lines when applying a code block
	-- 		enable_token_counting = true, -- Whether to enable token counting. Default to true.
	-- 		auto_add_current_file = true, -- Whether to automatically add the current file when opening a new chat. Default to true.
	-- 		auto_approve_tool_permissions = true, -- Default: auto-approve all tools (no prompts)
	-- 		-- Examples:
	-- 		-- auto_approve_tool_permissions = false,                -- Show permission prompts for all tools
	-- 		-- auto_approve_tool_permissions = {"bash", "str_replace"}, -- Auto-approve specific tools only
	-- 		---@type "popup" | "inline_buttons"
	-- 		confirmation_ui_style = "inline_buttons",
	-- 		--- Whether to automatically open files and navigate to lines when ACP agent makes edits
	-- 		---@type boolean
	-- 		acp_follow_agent_locations = true,
	-- 	},
	-- 	suggestion = {
	-- 		debounce = 600,
	-- 		throttle = 600,
	-- 	},
	-- },
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"MunifTanjim/nui.nvim",
	-- 	--- The below dependencies are optional,
	-- 	"nvim-mini/mini.pick", -- for file_selector provider mini.pick
	-- 	"nvim-telescope/telescope.nvim", -- for file_selector provider telescope
	-- 	"hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
	-- 	"ibhagwan/fzf-lua", -- for file_selector provider fzf
	-- 	"stevearc/dressing.nvim", -- for input provider dressing
	-- 	"folke/snacks.nvim", -- for input provider snacks
	-- 	"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
	-- 	"zbirenbaum/copilot.lua", -- for providers='copilot'
	-- 	{
	-- 		-- support for image pasting
	-- 		"HakonHarnes/img-clip.nvim",
	-- 		event = "VeryLazy",
	-- 		opts = {
	-- 			default = {
	-- 				embed_image_as_base64 = false,
	-- 				prompt_for_file_name = false,
	-- 				drag_and_drop = {
	-- 					insert_mode = true,
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- 	{
	-- 		-- Make sure to set this up properly if you have lazy=true
	-- 		"MeanderingProgrammer/render-markdown.nvim",
	-- 		opts = {
	-- 			file_types = { "markdown", "Avante" },
	-- 		},
	-- 		ft = { "markdown", "Avante" },
	-- 	},
	-- },
}
